### ISSUE TITLE
Ajuda se possível.

### ISSUE THREAD

**Issue by DjRafael50** [jailsonsb2/player_html#1]
Olá amigo, gostei realmente do seu projeto, mas como sou leigo não sei como fazer para funcionar corretamente. Percebi que as músicas que tem no nome do artis ponto e vírgula acabam não funcionando, teria como tirar pela api esse ; , pois retorna erro no iTunes, não consegui mudar para Deezer, no dizer em outro player não tem esse problema com exemplo: GET LOW
Lil Jon & The East Side Boyz; Ying Yang Twins. Todos as canções que tem mais de um artista tem esse ;

Desculpa encomendar, se puder dar uma luz te agradeço. Obrigado

**Comment by jailsonsb2** [comment]
Seria mais interessante você renomear as músicas não?

**Comment by DjRafael50** [comment]
Pensei nisso, vou ver aqui. Obrigado
